apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-jul5-8-config-ns
spec:
  pipelineSpec:
    tasks:
      - name: configure-namespace
        taskRef:
          kind: Task
          params:
            - name: kind
              value: task
            - name: name
              value: rhtap-dev-namespace-setup
            - name: namespace
              value: rhtap
          resolver: cluster